1 - update awemsome-flameshot   - fix bug when flameshot gui cancelled   useful for run this script from keybind

diff --git a/awesome-flameshot b/awesome-flameshot
--- a/awesome-flameshot
+++ b/awesome-flameshot
@@ -48,7 +48,7 @@ function check() {
 
         echo -e "\n\n${Light_Cyan} [+] SUMMARY |${Light_Red} FAILED ${NoColor}"
         _end_job_=$(date +%s)
-        summary $_start_job_ $_end_job_
+        summary $_start_job_ $_end_job_ 'failed'
         exit 1
     fi
 }
@@ -130,13 +130,16 @@ function summary() {
     hours=$((_runtime_job_ / 3600)); minutes=$(( (_runtime_job_ % 3600) / 60 )); seconds=$(( (_runtime_job_ % 3600) % 60 ))
 
     printf "%s %s\n" "  |--[+] Elapsed Time : " "$hours : $minutes : $seconds"
-    printf "%s %s" "  |--[+] Output File  : " "$_target_file_"
 
-    xclip -selection clipboard -t image/png -i $_target_file_ >> $_LOG_FILE_ 2>&1
-    if [[ $? -eq 0 ]]; then
-        echo -e "${Light_Green} (Copied to Clipboard) ${NoColor}"
-    else
-        echo -e "${Light_Red} (Copy to Clipboard Failed) ${NoColor}"
+    if [[ $3 != "failed" ]]; then
+        printf "%s %s" "  |--[+] Output File  : " "$_target_file_"
+
+        xclip -selection clipboard -t image/png -i $_target_file_ >> $_LOG_FILE_ 2>&1
+        if [[ $? -eq 0 ]]; then
+            echo -e "${Light_Green} (Copied to Clipboard) ${NoColor}"
+        else
+            echo -e "${Light_Red} (Copy to Clipboard Failed) ${NoColor}"
+        fi
     fi
 
     _error_count_=$(cat $_LOG_FILE_ 2> /dev/null | wc -l)
